# Generated by Django 6.0 on 2026-01-08 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='Abbreviation')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('date_of_establishment', models.DateField(blank=True, null=True, verbose_name='Date of Establishment')),
                ('default_currency', models.CharField(default='USD', max_length=10, verbose_name='Default Currency')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='Tax ID')),
                ('default_letter_head', models.CharField(blank=True, max_length=200, verbose_name='Default Letter Head')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domain')),
                ('is_parent_company', models.BooleanField(default=False, verbose_name='Is Parent Company (Group)')),
                ('registration_details', models.TextField(blank=True, verbose_name='Registration Details')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disable')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is Group')),
                ('company_type', models.CharField(blank=True, choices=[('regular', 'Regular'), ('subsidiary', 'Subsidiary'), ('branch', 'Branch'), ('holding', 'Holding')], default='regular', max_length=20)),
                ('account_type', models.CharField(blank=True, choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20, verbose_name='Account Type')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Rate')),
                ('balance_must_be', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('both', 'Both')], default='both', max_length=10, verbose_name='Balance Must Be')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='finance.company', verbose_name='Parent Company')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
