# Generated by Django 6.0 on 2026-01-08 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Account Name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disable')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is Group')),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, verbose_name='Currency')),
                ('account_type', models.CharField(blank=True, choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20, verbose_name='Account Type')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Rate')),
                ('balance_must_be', models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit'), ('both', 'Both')], default='both', max_length=10, verbose_name='Balance Must Be')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='finance.account', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'account_number')},
            },
        ),
    ]
