# Generated by Django 6.0 on 2026-01-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=50, unique=True, verbose_name='Invoice ID')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Invoice Number')),
                ('date', models.DateField(verbose_name='Invoice Date')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('supplier_vat', models.CharField(blank=True, max_length=50, verbose_name='Supplier VAT')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_vat', models.CharField(blank=True, max_length=50, verbose_name='Customer VAT')),
                ('amount_before_vat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Before VAT')),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total VAT')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount')),
                ('qr_code_present', models.BooleanField(default=False, verbose_name='QR Code Present')),
                ('qr_code_data', models.TextField(blank=True, verbose_name='QR Code Data')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('return', 'Return')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
