# Generated by Django 6.0 on 2026-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(max_length=56, null=True),
        ),
    ]
