# Generated by Django 6.0 on 2026-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_login_username_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56, null=True)),
                ('last_name', models.CharField(max_length=56, null=True)),
                ('username', models.CharField(max_length=56, null=True)),
                ('email', models.EmailField(max_length=56, null=True)),
                ('password', models.CharField(max_length=56)),
                ('confirm_password', models.CharField(max_length=56)),
            ],
        ),
    ]
