# Generated by Django 6.0 on 2026-01-12 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
    ]
