# Generated by Django 6.0 on 2026-01-12 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_supplier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='finance.company'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('company', 'name')},
        ),
    ]
