# Generated by Django 6.0 on 2026-01-12 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_supplier_company_alter_supplier_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.supplier', verbose_name='Supplier'),
        ),
    ]
