# Generated by Django 6.0 on 2026-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_invoice_supplier_name_invoice_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gst_category',
            field=models.CharField(choices=[('registered', 'Registered Regular'), ('registered_composition', 'Registered Composition'), ('unregistered', 'Unregistered'), ('sez', 'SEZ'), ('overseas', 'Overseas'), ('deemed_export', 'Deemed Export'), ('uin', 'UIN Holders'), ('tax_deductor', 'Tax Deductor'), ('tax_collector', 'Tax Collector'), ('input_service_distributor', 'Input Service Distributor')], default='unregistered', max_length=40, verbose_name='GST Category'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('partnership', 'Partnership')], default='company', max_length=20, verbose_name='Supplier Type'),
        ),
    ]
