# Generated by Django 6.0 on 2026-01-13 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_supplier_gst_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin_uin', models.CharField(blank=True, help_text='Optional GSTIN for autofill', max_length=30, verbose_name='GSTIN / UIN')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('partnership', 'Partnership')], default='company', max_length=20, verbose_name='Customer Type')),
                ('gst_category', models.CharField(choices=[('registered', 'Registered Regular'), ('registered_composition', 'Registered Composition'), ('unregistered', 'Unregistered'), ('sez', 'SEZ'), ('overseas', 'Overseas'), ('deemed_export', 'Deemed Export'), ('uin', 'UIN Holders'), ('tax_deductor', 'Tax Deductor'), ('tax_collector', 'Tax Collector'), ('input_service_distributor', 'Input Service Distributor')], default='unregistered', max_length=40, verbose_name='GST Category')),
                ('contact_first_name', models.CharField(blank=True, max_length=100, verbose_name='First Name')),
                ('contact_last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email ID')),
                ('contact_mobile', models.CharField(blank=True, max_length=30, verbose_name='Mobile Number')),
                ('preferred_billing', models.BooleanField(default=False, verbose_name='Preferred Billing Address')),
                ('preferred_shipping', models.BooleanField(default=False, verbose_name='Preferred Shipping Address')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City/Town')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, default='Pakistan', max_length=100, verbose_name='Country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='finance.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
