# Generated by Django 6.0 on 2026-01-15 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_remove_invoice_customer_name_invoice_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=200, verbose_name='Budget Series')),
                ('budget_against', models.CharField(choices=[('cost_center', 'Cost Center'), ('project', 'Project')], max_length=200, verbose_name='Budget Against')),
                ('fiscal_year_from', models.CharField(choices=[('2025-2026', '2025-2026')], max_length=20, verbose_name='Fiscal Year From')),
                ('fiscal_year_to', models.CharField(choices=[('2025-2026', '2025-2026')], max_length=20, verbose_name='Fiscal Year To')),
                ('distribution', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half-yearly', 'Half-Yearly'), ('yearly', 'Yearly')], max_length=200, verbose_name='Distribution')),
                ('cost_center', models.CharField(max_length=200, verbose_name='Cost Center')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Budget Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.account', verbose_name='Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Budgets',
                'ordering': ['-fiscal_year_from', 'series'],
            },
        ),
    ]
