# Generated by Django 6.0 on 2026-01-15 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_costcenter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='cost_center_number',
            field=models.CharField(blank=True, help_text='Will be used as prefix in Cost Center name', max_length=50, null=True, verbose_name='Cost Center Number'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Entries can only be made against non-group cost centers', verbose_name='Is Group'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='finance.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Cost Center Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.costcenter', verbose_name='Parent Cost Center'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'name')},
        ),
    ]
