# Generated by Django 6.0 on 2026-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_budget_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cost_center',
            field=models.CharField(max_length=200, verbose_name='Cost Center'),
        ),
    ]
