# Generated by Django 6.0 on 2026-01-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_budget_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cost_center',
            field=models.ForeignKey(limit_choices_to={'is_disabled': False, 'is_group': False}, on_delete=django.db.models.deletion.PROTECT, to='finance.costcenter'),
        ),
    ]
