# Generated by Django 6.0 on 2026-01-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_budget_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Dimension Name')),
                ('document_type', models.CharField(max_length=100, verbose_name='Document Type')),
            ],
            options={
                'verbose_name_plural': 'Accounting Dimensions',
                'ordering': ['name'],
            },
        ),
    ]
