# Generated by Django 6.0 on 2026-01-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_accountingdimension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountingDimension',
        ),
    ]
