# Generated by Django 6.0 on 2026-01-16 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_accountingdimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_center_allocations', to='finance.company', verbose_name='Company')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.costcenter', verbose_name='Cost Center')),
            ],
            options={
                'ordering': ['cost_center'],
                'unique_together': {('cost_center', 'company')},
            },
        ),
    ]
