# Generated by Django 6.0 on 2026-01-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_costcenterallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tax Item Template Title')),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST Rate (%)')),
                ('gst_treatment', models.CharField(max_length=100, verbose_name='GST Treatment')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_item_templates', to='finance.company', verbose_name='Company')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
