# Generated by Django 6.0 on 2026-01-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_taxitemtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tax Category Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='taxitemtemplate',
            name='gst_treatment',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('nil_rated', 'Nil-Rated'), ('exempted', 'Exempted'), ('non_gst', 'Non-GST')], max_length=100, verbose_name='GST Treatment'),
        ),
    ]
