# Generated by Django 6.0 on 2026-01-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_taxcategory_alter_taxitemtemplate_gst_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcategory',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='taxcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tax Category Title'),
        ),
    ]
