# Generated by Django 6.0 on 2026-01-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_taxcategory_options_remove_taxcategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase')], max_length=100, verbose_name='Tax Type')),
                ('shopping_cart_use', models.BooleanField(default=False, verbose_name='Shopping Cart Use')),
                ('customer_group', models.CharField(blank=True, max_length=100, verbose_name='Customer Group')),
                ('item', models.CharField(blank=True, max_length=200, verbose_name='Item')),
                ('item_group', models.CharField(blank=True, max_length=100, verbose_name='Item Group')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Billing City')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='Shipping City')),
                ('billing_county', models.CharField(blank=True, max_length=100, verbose_name='Billing County')),
                ('shipping_county', models.CharField(blank=True, max_length=100, verbose_name='Shipping County')),
                ('billing_state', models.CharField(blank=True, max_length=100, verbose_name='Billing State')),
                ('shipping_state', models.CharField(blank=True, max_length=100, verbose_name='Shipping State')),
                ('billing_zipcode', models.CharField(blank=True, max_length=20, verbose_name='Billing Zipcode')),
                ('shipping_zipcode', models.CharField(blank=True, max_length=20, verbose_name='Shipping Zipcode')),
                ('billing_country', models.CharField(blank=True, max_length=100, verbose_name='Billing Country')),
                ('shipping_country', models.CharField(blank=True, max_length=100, verbose_name='Shipping Country')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='finance.company', verbose_name='Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='finance.customer', verbose_name='Customer')),
                ('sales_tax_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_tax_rules', to='finance.taxitemtemplate', verbose_name='Sales Tax Template')),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='finance.taxcategory', verbose_name='Tax Category')),
            ],
        ),
    ]
