# Generated by Django 6.0 on 2026-01-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_taxrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxWithholdingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category Name')),
                ('deduct_tax_on_basis', models.CharField(choices=[('Net Total', 'Net Total'), ('Gross Total', 'Gross Total')], default='Net Total', max_length=50, verbose_name='Deduct Tax On Basis')),
                ('round_off_tax_amount', models.BooleanField(default=False, help_text='Checking this will round off the tax amount to the nearest integer', verbose_name='Round Off Tax Amount')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('only_deduct_on_excess', models.BooleanField(default=False, help_text='Tax withheld only for amount exceeding cumulative threshold', verbose_name='Only Deduct Tax On Excess Amount')),
                ('entity', models.CharField(choices=[('Company', 'Company'), ('Company Assessee', 'Company Assessee'), ('Individual', 'Individual'), ('No PAN / Invalid PAN', 'No PAN / Invalid PAN')], default='Company', max_length=50, verbose_name='Entity')),
                ('disable_cumulative_threshold', models.BooleanField(default=False, help_text='When checked, only transaction threshold will be applied for transaction individually', verbose_name='Disable Cumulative Threshold')),
                ('disable_transaction_threshold', models.BooleanField(default=False, help_text='When checked, only cumulative threshold will be applied', verbose_name='Disable Transaction Threshold')),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategoryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account', verbose_name='Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company', verbose_name='Company')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.taxwithholdingcategory')),
            ],
            options={
                'verbose_name': 'Category Account Mapping',
            },
        ),
        migrations.CreateModel(
            name='TaxWithholdingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('tax_withholding_group', models.CharField(blank=True, max_length=100, verbose_name='Tax Withholding Group')),
                ('tax_withholding_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Tax Withholding Rate')),
                ('cumulative_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cumulative Threshold')),
                ('transaction_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Transaction Threshold')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.taxwithholdingcategory')),
            ],
            options={
                'verbose_name': 'Tax Withholding Rate',
            },
        ),
    ]
