# Generated by Django 6.0 on 2026-01-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_taxwithholdingcategory_taxcategoryaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(choices=[('2025-2026', '2025-2026')], max_length=20, verbose_name='Fiscal Year')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Certificate Number')),
                ('pan_number', models.CharField(blank=True, max_length=20, verbose_name='PAN Number')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(verbose_name='Valid To')),
                ('rate_of_tdas', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Rate of TDS')),
                ('certificate_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Certificate Limit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.company', verbose_name='Company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_certificates', to='finance.supplier', verbose_name='Supplier')),
                ('tax_withholding_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_certificates', to='finance.taxwithholdingcategory', verbose_name='Tax Withholding Category')),
            ],
        ),
    ]
