# Generated by Django 6.0 on 2026-01-22 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_deductioncertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_subtype', models.CharField(max_length=200, verbose_name='Bank Account Subtype Name')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Subtypes',
                'ordering': ['account_subtype'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=200, verbose_name='Bank Account Type Name')),
            ],
            options={
                'verbose_name_plural': 'Bank Account Types',
                'ordering': ['account_type'],
            },
        ),
        migrations.CreateModel(
            name='BankGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receiving', 'Receiving'), ('providing', 'Providing')], max_length=100, verbose_name='Bank Guarantee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('start_date', models.DateField(verbose_name='Start Date')),
            ],
            options={
                'verbose_name_plural': 'Bank Guarantees',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Bank Account Name')),
                ('bank', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('party_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('shareholder', 'Shareholder')], max_length=100, verbose_name='Party Type')),
                ('party', models.CharField(blank=True, max_length=200, verbose_name='Party')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('branch_code', models.CharField(blank=True, max_length=20, verbose_name='Branch Code')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Bank Account Number')),
                ('last_integration_date', models.DateField(blank=True, null=True, verbose_name='Last Integration Date')),
                ('account_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.bankaccountsubtype', verbose_name='Bank Account Subtype')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.bankaccounttype', verbose_name='Bank Account Type')),
            ],
            options={
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['name'],
            },
        ),
    ]
