# Generated by Django 6.0 on 2026-01-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_bankaccount_account_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.bankaccountsubtype', verbose_name='Bank Account Subtype'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='finance.bankaccounttype', verbose_name='Bank Account Type'),
        ),
    ]
