# Generated by Django 6.0 on 2026-01-26 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0030_alter_bankaccount_account_subtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnreconcilePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("Payment Entry", "Payment Entry"),
                            ("Journal Entry", "Journal Entry"),
                        ],
                        max_length=100,
                        verbose_name="Voucher Type",
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(max_length=100, verbose_name="Voucher Number"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unreconcile_payments",
                        to="finance.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unreconcile Payments",
                "ordering": ["-voucher_number"],
            },
        ),
    ]
