# Generated by Django 6.0 on 2026-01-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0031_unreconcilepayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unreconcilepayment",
            name="voucher_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Voucher Number"
            ),
        ),
        migrations.AlterField(
            model_name="unreconcilepayment",
            name="voucher_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Payment Entry", "Payment Entry"),
                    ("Journal Entry", "Journal Entry"),
                ],
                max_length=100,
                null=True,
                verbose_name="Voucher Type",
            ),
        ),
    ]
