# Generated by Django 6.0 on 2026-01-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0032_alter_unreconcilepayment_voucher_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessPaymentReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party",
                    models.CharField(blank=True, max_length=200, verbose_name="Party"),
                ),
                (
                    "party_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("customer", "Customer"),
                            ("supplier", "Supplier"),
                            ("employee", "Employee"),
                            ("shareholder", "Shareholder"),
                        ],
                        max_length=100,
                        verbose_name="Party Type",
                    ),
                ),
                (
                    "from_invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="From Invoice Date"
                    ),
                ),
                (
                    "to_invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="To Invoice Date"
                    ),
                ),
                (
                    "from_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="From Payment Date"
                    ),
                ),
                (
                    "to_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="To Payment Date"
                    ),
                ),
                (
                    "bank_cash_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_cash_process_payment_reconciliations",
                        to="finance.account",
                        verbose_name="Bank/Cash Account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_payment_reconciliations",
                        to="finance.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_payment_reconciliations",
                        to="finance.costcenter",
                        verbose_name="Cost Center",
                    ),
                ),
                (
                    "receivable_payable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_payment_reconciliations",
                        to="finance.account",
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Process Payment Reconciliations",
                "ordering": ["-from_invoice_date"],
            },
        ),
    ]
