# Generated by Django 6.0 on 2026-02-09 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0033_processpaymentreconciliation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dunning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning",
                        to="finance.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning",
                        to="finance.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
        ),
    ]
