# Generated by Django 6.0 on 2026-02-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0034_dunning"),
    ]

    operations = [
        migrations.CreateModel(
            name="DunningType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dunning_type", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning_type",
                        to="finance.company",
                        verbose_name="Company",
                    ),
                ),
            ],
        ),
    ]
